name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: npm install -g firebase-tools
        - run: npm install
        - run: npm run build
        - run: npm run export
        - run: firebase deploy --project latextra-cec3c --token ${{ secrets.FIREBASE_TOKEN }}
